GET http://localhost:3001/livros

###

POST http://localhost:3001/livros
Content-Type: application/json

{  
    "titulo": "Rumores da cidade",
    "autor": "Lucas Rocha"
}

###

PUT http://localhost:3001/livros/2
Content-Type: application/json

{
    "titulo": "Gravity Falls",
    "autor": "Alex Hirsch"
}

###

DELETE http://localhost:3001/livros/3